# Generated by Django 4.1.5 on 2023-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.CharField(default='buyer', max_length=50),
        ),
    ]
