# Generated by Django 4.1.5 on 2023-02-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_member_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lname',
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
