# Generated by Django 4.1.5 on 2023-02-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_member_fname_remove_member_lname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
