# Generated by Django 4.1.5 on 2023-02-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='dafault', max_length=250),
        ),
    ]
